### ISSUE TITLE
Question about method you wrote

### ISSUE THREAD

**Issue by cyberkm** [JoshuaLight/Pocket.Common#19]
public static bool Equivalence(this bool self, bool other) => !self && !other || self && other;

I am having troubles understanding what this code does. And will appreciate if you explain it to me.

If I understand correctly it is equal to self == other, right? Or any other difference?

**Comment by JoshuaLight** [comment]
Hi!

This is actually a nice question. I wrote `Equivalence` method for some scenario in my Unity project, and I think I didn't realize at first time that this is really just `==` operator on `bool` but in terms of `!`, `&&` and `||` logical operators.

I think I will remove it, so thank you for your thoroughness.

**Comment by JoshuaLight** [comment]
@cyberkm 
Removed in [6f055a9](https://github.com/JoshuaLight/Pocket.Common/commit/6f055a920b315a89f4d36a48bd22cd8b2947e11f). Thanks!
